export const site = {
  name: "Dirane Mekem",
  firstName: "Dirane",
  role: "Software Engineer, UI/UX Designer & créateur de contenu tech",
  roleShort: "Software Engineer & UI/UX Designer",
  tagline: "Je conçois des produits numériques utiles, élégants et performants.",
  description:
    "Dirane Mekem, Software Engineer, UI/UX Designer et créateur de contenu tech basé à Douala (Cameroun). Conception et développement d'applications web et mobiles avec React, Next.js, React Native et Supabase, design d'interfaces sur Figma, IA, automatisation, et partage de contenu tech sur les réseaux.",
  url: "https://www.dirane.me",
  locale: "fr_FR",
  email: "contact@dirane.me",
  phoneDisplay: "+237 697 60 93 87",
  phoneRaw: "237697609387",
  whatsappMessage: "Bonjour Dirane, je souhaite discuter d'un projet avec vous.",
  location: "Douala, Cameroun",
  cvPath: "/CV_Dirane_Mekem.pdf",
  available: true,
  keywords: [
    "Dirane Mekem",
    "développeur web Douala",
    "développeur Next.js Cameroun",
    "UI/UX designer Cameroun",
    "software engineer Douala",
    "développeur React Native",
    "freelance développeur Cameroun",
    "création site web Douala",
    "application mobile Cameroun",
    "créateur de contenu tech",
    "blog développement web",
  ],
  socials: {
    github: "https://github.com/diraneCode",
    linkedin: "https://www.linkedin.com/in/dirane-mekem-63b588273",
    tiktok: "https://www.tiktok.com/@diranecode",
    instagram: "https://instagram.com/diranecode33",
    x: "https://twitter.com/dirane_joker",
    facebook: "https://facebook.com/diranemekem",
    threads: "https://www.threads.net/@diranecode33",
    bento: "https://bento.me/dirane",
  },
  /** Chaîne principale de contenu tech (vidéos courtes). */
  content: {
    platform: "TikTok",
    handle: "@diranecode",
    url: "https://www.tiktok.com/@diranecode",
    pitch: "Astuces dev, coulisses de projets et design d'interfaces, en vidéos courtes.",
  },
  nav: [
    { label: "Accueil", href: "/#home", ariaLabel: "Aller à l'accueil" },
    { label: "À propos", href: "/#a-propos", ariaLabel: "En savoir plus sur moi" },
    { label: "Parcours", href: "/#parcours", ariaLabel: "Voir mon parcours" },
    { label: "Services", href: "/#services", ariaLabel: "Découvrir mes services" },
    { label: "Projets", href: "/#projets", ariaLabel: "Voir mes projets" },
    { label: "Art", href: "/#art", ariaLabel: "Voir ma galerie d'art" },
    { label: "Blog", href: "/blog", ariaLabel: "Lire mes articles" },
    { label: "Contact", href: "/#contact", ariaLabel: "Me contacter" },
  ],
} as const;

export const whatsappUrl = `https://wa.me/${site.phoneRaw}?text=${encodeURIComponent(site.whatsappMessage)}`;
